### ISSUE TITLE
looking for the .xlsx files that you use in evaluation part of the code

### ISSUE THREAD

**Issue by dfangnon** [Wangyixinxin/MRG-KG#2]
looking for the .xlsx files that you use in the evaluation part of the code:

report_bleubest.xlsx ; Results_diseaseV3_classfied-disease.xlsx .

Congratulations on this great work and for providing the resources about the code.

**Comment by Wangyixinxin** [comment]
Hi, sorry for the late reply. We have updated Aug_and_Eval.ipynb and all the required .xlsx files.
